name: Java Selenium TestNG with Allure Reports (Docker Grid)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.8.8'

      - name: Run Tests with Maven (Remote WebDriver)
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          echo "Running tests using Remote WebDriver at $SELENIUM_REMOTE_URL"
          mvn clean test -Dselenium.remote.url=$SELENIUM_REMOTE_URL

      - name: Generate Allure Report
        run: |
          mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
