name: Java Selenium TestNG with Allure Reports (Docker Grid)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Tests with Maven
        run: |
          echo "Running tests using hardcoded RemoteWebDriver at http://localhost:4444/wd/hub"
          mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
